ALTER TABLE "Kilai" ADD COLUMN IF NOT EXISTS "secretaryName" TEXT;
ALTER TABLE "Kilai" ADD COLUMN IF NOT EXISTS "panchayat" TEXT;
ALTER TABLE "Kilai" ADD COLUMN IF NOT EXISTS "villages" TEXT[];
ALTER TABLE "Kilai" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Kilai" ADD COLUMN IF NOT EXISTS "email" TEXT;
